### PR TITLE
Upgraded to Spring Boot 2.2

### PR DESCRIPTION
**Pull request by Buzzardo**
I upgraded the build files to Spring Boot 2.2.0, which necessitated changing the tests to use JUnit 5 and replacing the Gradle wrappers. I also noticed that I hadn't change the package of the /complete test path, so I did that, too.

### CODE REVIEW

**Comment by dsyer** [comment]
Obsoleted by f1af974b

**Comment by Buzzardo** [comment]
Greg changed the version in the readme file. I changed the version in the build files and changed the tests to use Junit 5 and updated the Gradle wrappers. It's a different set of work.

**Comment by dsyer** [comment]
I guess it might be different, but this change conflicts, so can you rebase it?

**Comment by Buzzardo** [comment]
Thanks, Dave. :)

**Pull request merged**
